batch_size: 256
data_name: ADReSS2020
data_type: text
dropout: 0.5
early_stop: 1000
epochs: 1000
feature_type: None
flatten: false
hidden_size: 16
lr: 1.0e-05
model: Transformer
output_size: 2
wave_type: full
