audio_type: None
batch_size: 256
data_name: ADReSS2020
data_type: text
dropout: 0.25
early_stop: 1000
epochs: 1000
flatten: false
hidden_size: 64
lr: 1.0e-05
model: Transformer
output_size: 2
text_feature: modernbert-base
text_type: full
wave_type: full
