# Default configuration parameters

# Data
data_path: "data/raw/your_data.csv"  # Path to your raw data

# Model hyperparameters
learning_rate: 0.001
epochs: 10
batch_size: 32

# Model
model_path: "models/saved_models/your_model.pth"
model_save_name: "your_model.pth" # File name to save the model

# Training
device: "cpu"  # Options: "cpu" or "cuda"
experiment_name: "default_experiment"

# Add other configuration parameters as needed
